config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  #  Cambia la url base de /photos a /fotos, manteniendo el resto en el modelo photos y controlador photos
  resources :fotos, as: :photos, controller: :photos, path_names: { new: 'nuevo', edit: 'editar' } # do
  #   member do
  #     # /fotos/:id/preview
  #     get 'preview'
  #   end

  #   collection do
  #     # /fotos/admin
  #     get 'admin'
  #   end
  # end

  root to: 'main#hello'

  get 'bienvenida', to: 'main#hi'
  post 'hi', to: 'main#greetings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  image_url  :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  todo_id    :integer          not null
#
# Indexes
#
#  index_photos_on_todo_id  (todo_id)
#
# Foreign Keys
#
#  todo_id  (todo_id => todos.id)
#
class Photo < ApplicationRecord
  validates :title, presence: true, uniqueness: { message: '%{value} es un valor que ya fue usado para %{attribute}' }
  validates :image_url, presence: true, format: { with: /.\.(png|jpeg|jpg|gif)/, message: 'La URL no es válida' }

  belongs_to :todo
  has_and_belongs_to_many :tags

  # Photo.latest(1)
  scope :latest, ->(limit) { order('id desc').limit(limit) }

  def self.paginate(page = 1, per_page = 15)
    Photo.order('id desc').offset((page - 1) * per_page).limit(per_page)
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  color      :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
    has_and_belongs_to_many :photos
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  due_date    :datetime
#  priority    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Todo < ApplicationRecord
  validates :title, presence: true
  validate :due_date_is_valid

  before_validation :set_randome_title_if_nil

  # dependent: :destroy permite, al elminar un todo tambien eliminar los registros asociados, en este caso, fotos
  has_many :photos, dependent: :destroy

  private

  def due_date_is_valid
    errors.add(:due_date, 'La fecha de entrega ya pasó.') if due_date < Datetime.now
  end

  def set_randome_title_if_nil
    self.title ||= (0...8).map { rand(65..90).chr }.join
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def hello; end

  def hi; end

  def greetings
    @name = params[:name]
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[show update destroy edit]

  def index
    @photos = Photo.all
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @photo }
    end
  end

  def new
    session[:intentos] = session[:intentos] ? session[:intentos] + 1 : 1
  end

  def create
    photo = Photo.new(photo_params)

    respond_to do |format|
      if photo.save
        format.html { redirect_to photo, notice: 'Todo salió perrón' }
        format.json { render json: photo, status: :created }
      else
        format.html { redirect_back fallback_location: photos_path, notice: 'Algo salió mal' }
      end
    end
  end

  # GET /photos/:id/edit
  def edit
    @photo
  end

  # PUT/PATCH /photos/:id
  def update
    @photo.update(photo_params)

    redirect_to @photo
  end

  # DELETE /photos/:id
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_path }
      format.json { head :ok }
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image_url)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show; end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authenticator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p><%= notice %></p>
  <% end %>
  
    <%= yield :sidebar_options %>

    <%= yield %>
  </body>
</html>

app/views/main/greetings.html.erb
<h1>
    Hola <%= @name %>
</h1>

app/views/main/hello.html.erb
<h1>Hola mundo</h1>
<%= link_to 'Inicio', root_url %>
<%= link_to 'Ir al saludo', bienvenida_path %>

app/views/main/hi.html.erb
<%= form_with url:"/hi", method: :post do |f|%>
   <div>
     <%= label_tag :name, "Nombre"%>
    <%= f.text_field :name%>
   </div>
   <div>
    <%= submit_tag "Enviar" %>
   </div>
<% end %>

app/views/photos/edit.html.erb
<%= form_with model: @photo do |f| %>
   <div>
        <%= f.label :title%>
        <%= f.text_field :title%>
    </div>

    <div>
        <%= f.label :image_url%>
        <%= f.url_field :image_url%>

    </div>

    <%= f.submit "Guardar"%>
<%end%>

<div>
    <%= link_to 'Cancelar', photo_path(@photo.id) %>
</div>

app/views/photos/index.html.erb
<h1>Fotos</h1>

<%= content_for :sidebar_options do %>
    <p>Hola desde fotos</p>
<% end %>

<% @photos.each do |photo|%>
    <div>
        <h2>
            <%= photo.title %>
        </h2>
        <%= image_tag photo.image_url %>
        <div>
         <%= link_to 'Ver más', photo %>
        </div>
    </div>
<% end %>

app/views/photos/new.html.erb
<p>Intentos: <%= session[:intentos] %></p>
<!-- <form action="<%= photos_path %>" method="post"> -->
<%= form_with model: @photo do |f|%>
    <div>
        <%= f.label :title%>
        <%= f.text_field :title%>
    </div>

    <div>
        <%= f.label :image_url%>
        <%= f.url_field :image_url%>

    </div>

    <%= f.submit "Enviar"%>
<%end%>

app/views/photos/show.html.erb
<h1>Foto</h1>
    <div>
        <h2>
            <%= @photo.title %>
        </h2>
        <%= image_tag @photo.image_url %>
        <div>
        <%= link_to 'Editar', edit_photo_path %>
            <%= link_to 'Eliminar', @photo, method: :delete%>
        </div>
        <div>
            <%= link_to 'Regresar', photos_path %>
        </div>
    </div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

   <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
       <td><%= tweet.username %></td>
        <td><%= tweet.body %></td>
        
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<p>
  <strong>Username:</strong>
  <%= @tweet.username unless @tweet.username.nil? %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>